project:
  type: website
  output-dir: docs

website:
  site-url: "https://emitanaka.org/EDV-workshop/"
  repo-url: "https://github.com/emitanaka/EDV-workshop"
  title: "Effective Data Visualisation with R"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
     - sketchy
     - assets/custom.scss
    css: assets/styles.css
    toc: true
    include-after: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>

